Added styles for news teaser view.
ATLAS-Illinois/Illinois-Framework-Theme pull request #553
Opened 2021-11-29 20:26 UTC by robgasc

2021-11-29 20:42 UTC, robgasc commented
Should close #532. Builds fine on local.

2021-11-29 20:42 UTC, trubach requested changes
See my comments on the _node.news.scss file

2021-11-29 20:42 UTC, trubach commented on scss/illinois-framework/_node.news.scss
> +
@robgasc  - A couple things:

1) Can you group these together in SASS? If you see above, there's a few classes that are grouped with curly braces. I think you should be able to have one .spotlight-list-item declaration, and then the sub class declarations grouped within that.

2) Please add a short comment above these to describe what these styles are for

2021-11-29 20:49 UTC, robgasc commented on scss/illinois-framework/_node.news.scss
> +
Take a look; Thanks for the catch. Added a group for the news-list-teaser class, and a comment clarifying the styles are for the teaser.

2021-11-29 20:51 UTC, robgasc commented
Also needs https://github.com/web-illinois/illinois_framework_core/pull/52 merged to be functional.

2021-11-30 15:16 UTC, trubach approved these changes

2021-11-30 15:24 UTC, merged