Mods to add related_people to node--news template
ATLAS-Illinois/Illinois-Framework-Theme pull request #987
Opened 2024-03-06 16:11 UTC by hpleas

Add related people link to News pages

2024-03-08 14:23 UTC, trubach requested changes
Hey @hpleas - it looks like the spacing got switched from 2 spaces to 4 spaces. Can you switch it back to 2 spaces and resubmit? Thanks!

2024-03-08 15:30 UTC, hpleas commented
Hi @trubach,

I don't think this needs to be resubmitted.  It's pushed and you should be able to see the adjustments in the existing pull request.  Let me know if its in the format you would like.

Henry

2024-03-19 21:04 UTC, trubach approved these changes

2025-03-13 18:30 UTC, trubach commented
Closing - no longer needed with the updated node--news.html.twig template, which honors the view display.

2025-03-13 18:30 UTC, closed without merging